name: Container build, scan and push

on: [push, pull_request]

jobs:
  build-and-scan: # First job: Build and scan
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    outputs:
      scan_status: ${{ steps.scan.outcome }} # Output the scan outcome
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install required packages
        run: npm install @actions/core

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build my image
        id: build-image
        run: docker build -t my-app:latest .

      - name: Scan image
        id: scan
        uses: sysdiglabs/scan-action@v5
        with:
          sysdig-secure-url: https://app.au1.sysdig.com
          image-tag: my-app:latest
          sysdig-secure-token: ${{ secrets.SECURE_API_TOKEN }}
          skip-summary: true

  check-scan-status:
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Check scan status (Shell Script)
        id: check_scan_status_script
        run: |
          if [[ "${{ needs.build-and-scan.outputs.scan_status }}" == "success" ]]; then
            echo "Scan passed"
            echo "push_to_ecr=true" >> "$GITHUB_OUTPUT"
          else
            echo "Scan failed"
            echo "push_to_ecr=false" >> "$GITHUB_OUTPUT"
          fi

  deploy: # Third job: Deploy to ECR
    needs: check-scan-status
    runs-on: ubuntu-latest
    if: |
     echo "Value of push_to_ecr: ${{ needs.check-scan-status.outputs.push_to_ecr }}"
     needs.check-scan-status.outputs.push_to_ecr == 'true'
    permissions:
        id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::288761737678:role/iam-ecr-full-access
          aws-region: ap-southeast-2

      - name: Push to ECR
        uses: hands-lab/push-ecr-action@v1
        with:
         image: my-app
         aws-access-key-id: ${{ secret.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secret.AWS_SECRET_ACCESS_KEY }}
         aws-account-id: ${{ secret.AWS_ACCOUNT_ID }}
         aws-region: ap-southeast-2
         repository-name: 288761737678.dkr.ecr.ap-southeast-2.amazonaws.com/sysdig
         image-tag: ${{ github.sha }}
