name: Container build, scan and push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build my image
        id: build-image
        run: docker build -t my-app:latest .

      - name: Scan image
        id: scan
        uses: sysdiglabs/scan-action@v5 # Or latest version
        with:
          sysdig-secure-url: https://app.au1.sysdig.com # Replace with your Sysdig region URL
          image-tag: my-app:latest
          sysdig-secure-token: ${{ secrets.SECURE_API_TOKEN }} # Make sure this secret is set
          skip-summary: true

      - name: Check scan status and control push
        id: check_scan_status
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const core = require('@actions/core');
              console.log("Context:", JSON.stringify(context, null, 2));
              console.log("Steps:", JSON.stringify(steps, null, 2));

              if (steps.scan && steps.scan.outputs && steps.scan.outputs.status === 'success') {
                console.log('Scan passed, proceeding to ECR push');
                core.setOutput('push_to_ecr', 'true');
              } else {
                console.log('Scan failed or status output not found. Build stopped.');
                core.setFailed('Build failed due to scan policy violation');
                core.setOutput('push_to_ecr', 'false');
              }
            } catch (error) {
              console.error("Error in github-script:", error);
              core.setFailed(`JavaScript error: ${error.message}`);
            }

      - name: Configure AWS credentials
        if: steps.check_scan_status.outputs.push_to_ecr == 'true'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: aarn:aws:iam::288761737678:role/iam-ecr-full-access
          aws-region: ap-southeast-2 # Replace with your AWS region

      - name: Push to ECR
        if: steps.check_scan_status.outputs.push_to_ecr == 'true'
        uses: aws-actions/amazon-ecr-push@v2 # Use the official AWS action
        with:
          aws-region: ap-southeast-2 # Replace with your AWS region
          repository-name: 288761737678.dkr.ecr.ap-southeast-2.amazonaws.com/sysdig # Replace with your ECR repository name (without the account ID prefix)
          image-tag: ${{ github.sha }}
