name: Container build, scan and push

on: [push, pull_request]

jobs:
  build-and-scan: # First job: Build and scan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      scan_status: ${{ steps.scan.outcome }} # Output the scan outcome
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install required packages
        run: npm install @actions/core

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build my image
        id: build-image
        run: docker build -t my-app:latest .

      - name: Scan image
        id: scan
        uses: sysdiglabs/scan-action@v5
        with:
          sysdig-secure-url: https://app.au1.sysdig.com
          image-tag: my-app:latest
          sysdig-secure-token: ${{ secrets.SECURE_API_TOKEN }}
          skip-summary: true

  check-scan-status: # Second job: Check the scan status (JavaScript logic)
    needs: build-and-scan # Run after build and scan
    runs-on: ubuntu-latest
    outputs:
      push_to_ecr: ${{ steps.check_scan_status_script.outputs.push_to_ecr }}
    steps:
      - name: Check scan status
        id: check_scan_status_script
        uses: actions/github-script@v6
        with:
          script: |
            const core = require('@actions/core');
            try {
              const scanStatus = context.needs.build_and_scan.outputs.scan_status;
              console.log("Scan Status:", scanStatus);

              if (scanStatus === 'success') {
                console.log('Scan passed, proceeding to ECR push');
                core.setOutput('push_to_ecr', 'true');
              } else {
                console.log('Scan failed or status not found. Build stopped.');
                core.setFailed('Scan failed or did not produce an output'); // More informative message
                core.setOutput('push_to_ecr', 'false');
              }
            } catch (error) {
              console.error("Error in github-script:", error);
              core.setFailed(`JavaScript error: ${error.message}`);
            }

  deploy: # Third job: Deploy to ECR
    needs: check-scan-status
    runs-on: ubuntu-latest
    if: needs.check-scan-status.outputs.push_to_ecr == 'true'
    permissions:
        id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::288761737678:role/iam-ecr-full-access
          aws-region: ap-southeast-2

      - name: Push to ECR
        uses: aws-actions/amazon-ecr-push@v2
        with:
          aws-region: ap-southeast-2
          repository-name: 288761737678.dkr.ecr.ap-southeast-2.amazonaws.com/sysdig
          image-tag: ${{ github.sha }}
