name: Container build, scan and push

on: [push, pull_request]

jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build my image
      run: docker build -t my-app:latest .
       
    - name: Scan image
      id: scan
      uses: sysdiglabs/scan-action@v5
      with:
          sysdig-secure-url: https://app.au1.sysdig.com
          image-tag: my-app:latest
          sysdig-secure-token: ${{ secrets.SECURE_API_TOKEN }}
          skip-summary: true
