name: Container build, scan and push

on: [push, pull_request]

jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build my image
        id: build-image
        run: docker build -t my-app:latest .

      - name: Scan image
        id: scan
        uses: sysdiglabs/scan-action@v5
        with:
          sysdig-secure-url: https://app.au1.sysdig.com
          image-tag: my-app:latest  # Use the built image tag
          sysdig-secure-token: ${{ secrets.SECURE_API_TOKEN }}
          skip-summary: true

      - name: Check scan status
        run: |
          if [[ ${{ steps.scan.outcome }} == "success" ]]; then
            echo "Scan passed, proceeding to ECR."
          else
            echo "Scan failed! Build process stopped."
            exit 1  # Halt the workflow execution
          fi

      - name: Login to Amazon ECR (Conditional)
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        if: ${{ steps.scan.outcome == 'success' }}  # Only run if scan passes
        with:
          aws-region: ap-southeast-2  # Replace with your region
          role-to-assume: arn:aws:iam::288761737678:role/iam-ecr-full-access  # Replace with your IAM role ARN

      - name: Build and push image to ECR (Conditional)
        id: build-push-ecr
        uses: aws-actions/amazon-ecr-push@v2
        if: ${{ steps.scan.outcome == 'success' }}  # Only run if scan passes
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          image-tag: my-app:latest  # Use the built image tag
          image-digest: ${{ steps.build-image.outputs.digest }}  # Optional: Use the digest for immutability
